# Generated by Django 5.0.2 on 2024-03-02 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesLockUnlock',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=50)),
                ('device_ip', models.CharField(max_length=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('user_device', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13, verbose_name='Phone_number')),
                ('image', models.ImageField(upload_to='users_image/')),
                ('sex', models.CharField(choices=[('Child', 'Child'), ('Men', 'Men'), ('Women', 'Women'), ('No', '-----')], default='No', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=255)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
