# Generated by Django 5.0.2 on 2024-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceslockunlock',
            name='is_safe',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
