# Generated by Django 5.0.2 on 2024-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_deviceslockunlock_is_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceslockunlock',
            name='is_safe',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
