version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      image: sqlite3:latest
      stdin_open: true
      tty: true
      volumes:
        - db