# Generated by Django 5.0.2 on 2024-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
